// Service tokens for dependency injection
export const SERVICE_TOKENS = {
  // API Services
  API_SERVICE: 'API_SERVICE',
  MOCK_API_SERVICE: 'MOCK_API_SERVICE',
  REAL_API_SERVICE: 'REAL_API_SERVICE',

  // Storage Services
  STORAGE_SERVICE: 'STORAGE_SERVICE',
  ASYNC_STORAGE_SERVICE: 'ASYNC_STORAGE_SERVICE',

  // Authentication Services
  AUTH_SERVICE: 'AUTH_SERVICE',
  TOKEN_SERVICE: 'TOKEN_SERVICE',

  // Task Services
  TASK_SERVICE: 'TASK_SERVICE',
  CATEGORY_SERVICE: 'CATEGORY_SERVICE',

  // Utility Services
  LOGGER_SERVICE: 'LOGGER_SERVICE',
  VALIDATION_SERVICE: 'VALIDATION_SERVICE',
  RETRY_SERVICE: 'RETRY_SERVICE',
  PERFORMANCE_SERVICE: 'PERFORMANCE_SERVICE',

  // Configuration Services
  CONFIG_SERVICE: 'CONFIG_SERVICE',
  ENVIRONMENT_SERVICE: 'ENVIRONMENT_SERVICE',

  // Navigation Services
  NAVIGATION_SERVICE: 'NAVIGATION_SERVICE',

  // Theme Services
  THEME_SERVICE: 'THEME_SERVICE',

  // Analytics Services
  ANALYTICS_SERVICE: 'ANALYTICS_SERVICE',
  CRASH_REPORTING_SERVICE: 'CRASH_REPORTING_SERVICE',

  // Notification Services
  NOTIFICATION_SERVICE: 'NOTIFICATION_SERVICE',
  PUSH_NOTIFICATION_SERVICE: 'PUSH_NOTIFICATION_SERVICE',

  // Offline Services
  OFFLINE_SERVICE: 'OFFLINE_SERVICE',
  SYNC_SERVICE: 'SYNC_SERVICE',

  // Error Handling Services
  ERROR_HANDLER_SERVICE: 'ERROR_HANDLER_SERVICE',
  ERROR_REPORTING_SERVICE: 'ERROR_REPORTING_SERVICE',

  // Security Services
  ENCRYPTION_SERVICE: 'ENCRYPTION_SERVICE',
  SECURITY_SERVICE: 'SECURITY_SERVICE',

  // Cache Services
  CACHE_SERVICE: 'CACHE_SERVICE',
  MEMORY_CACHE_SERVICE: 'MEMORY_CACHE_SERVICE',

  // Network Services
  NETWORK_SERVICE: 'NETWORK_SERVICE',
  CONNECTIVITY_SERVICE: 'CONNECTIVITY_SERVICE',

  // Device Services
  DEVICE_SERVICE: 'DEVICE_SERVICE',
  PERMISSION_SERVICE: 'PERMISSION_SERVICE',

  // Localization Services
  I18N_SERVICE: 'I18N_SERVICE',
  TRANSLATION_SERVICE: 'TRANSLATION_SERVICE',

  // Feature Flags
  FEATURE_FLAG_SERVICE: 'FEATURE_FLAG_SERVICE',

  // Background Services
  BACKGROUND_SERVICE: 'BACKGROUND_SERVICE',
  WORKER_SERVICE: 'WORKER_SERVICE',
} as const;

export type ServiceToken = typeof SERVICE_TOKENS[keyof typeof SERVICE_TOKENS];

export default SERVICE_TOKENS; 